In [1]:
import tensorflow as tf

In [2]:
from tensorflow.keras.datasets import reuters
(train_data, train_labels), (test_data, test_labels) = reuters.load_data(num_words=10000)

2113536/2110848 [==============================] - 2s 1us/step


In [4]:
print(len(train_data))
print(len(test_data))

8982
2246


In [6]:
#Manual One Hot Encoding
import numpy as np
def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1
    return results
x_train = vectorize_sequences(train_data)
x_test = vectorize_sequences(test_data)

In [7]:
"""
Builtin tensorflow function for oneHotEncoding
from tensorflow.keras.np_utils import to_categorical
one_hot_train_labels = to_categorical(train_labels)
one_hot_test_labels = to_categorical(test_labels)
"""

'\nBuiltin tensorflow function for oneHotEncoding\nfrom tensorflow.keras.np_utils import to_categorical\none_hot_train_labels = to_categorical(train_labels)\none_hot_test_labels = to_categorical(test_labels)\n'

In [8]:
#Encoding Labels
def one_hot_labels(labels, dimension=46):
    results = np.zeros((len(labels), dimension))
    for i, label in enumerate(labels):
        results[i, label] = 1
    return results
one_hot_train_labels = one_hot_labels(train_labels)
one_hot_test_labels = one_hot_labels(test_labels)

In [9]:
print(one_hot_train_labels)
print(one_hot_test_labels)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [10]:
#Making Model
from tensorflow.keras import models, layers
model = models.Sequential()
model.add(layers.Dense(64, activation='relu', input_shape=(10000,)))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(46, activation='softmax'))

In [11]:
#Compiling the model
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [12]:
#Validation Data
x_val = x_train[:1000]
partial_x_train = x_train[1000:]
y_val = one_hot_train_labels[:1000]
partial_y_train = one_hot_train_labels[1000:]

In [14]:
history = model.fit(partial_x_train,
                    partial_y_train,
                    epochs=9,
                    batch_size=512,
                    validation_data=(x_val, y_val))

Train on 7982 samples, validate on 1000 samples
Epoch 1/9
7982/7982 [==============================] - 2s 215us/sample - loss: 0.1129 - accuracy: 0.9570 - val_loss: 1.0541 - val_accuracy: 0.8100
Epoch 2/9
7982/7982 [==============================] - 1s 175us/sample - loss: 0.1069 - accuracy: 0.9580 - val_loss: 1.0901 - val_accuracy: 0.8020
Epoch 3/9
7982/7982 [==============================] - 2s 201us/sample - loss: 0.1053 - accuracy: 0.9574 - val_loss: 1.1213 - val_accuracy: 0.8020
Epoch 4/9
7982/7982 [==============================] - 1s 167us/sample - loss: 0.1044 - accuracy: 0.9583 - val_loss: 1.1525 - val_accuracy: 0.7920
Epoch 5/9
7982/7982 [==============================] - 1s 170us/sample - loss: 0.1005 - accuracy: 0.9582 - val_loss: 1.2350 - val_accuracy: 0.7840
Epoch 6/9
7982/7982 [==============================] - 1s 181us/sample - loss: 0.1009 - accuracy: 0.9594 - val_loss: 1.1235 - val_accuracy: 0.8040
Epoch 7/9
7982/7982 [==============================] - 2s 235us/sample

In [15]:
results = model.evaluate(x_test, one_hot_test_labels)

2246/1 [================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

In [16]:
results

[1.4309625217984643, 0.7858415]